config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users do
  	resources :projects, only: [:new, :create]
  end
  resources :projects, only: [:index, :show, :destroy]

  root 'welcomes#index'

end

app/models/project.rb
class Project < ActiveRecord::Base

   belongs_to :recipient, class_name: "User", foreign_key: "recipient_id"
   belongs_to :sender, class_name: "User", foreign_key: "sender_id"
   scope :unread, -> { where read: false }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :projects, class_name: "Project", foreign_key: "recipient_id"
   has_many :sent_projects, class_name: "Project", foreign_key: "sender_id"

  after_create :send_notification

  def send_notification
  	AdminMailer.new_user(self).deliver_now
  end


# class User < ActiveRecord::Base
#    has_many :messages, class_name: "Message", foreign_key: "recipient_id"
#    has_many :sent_messages, class_name: "Message", foreign_key: "sender_id"
# end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  	before_action :set_recipient, only: [:new, :create]

	def index
		@projects = Project.all
	end

	def new
		@project = current_user.sent_projects.new

	end

	def create
     	@project.recipient_id = @recipient.id

		@project = current_user.sent_projects.new project_params
		@project.save
	end

	def show
		@project = Project.find(params[:id])
	end

	private

	def project_params
		params.require(:project).permit(:title, :description, :userforhire)
	end

	def set_recipient
	   @recipient = User.find params[:user_id]
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all.order('created_at DESC')
	end


	def show
		@user = User.find(params[:id])
		@project = Project.new
	end

    def sender
      @user = User.find(params[:id])
    end

    def recipient
      @user = User.find(params[:id])
    end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aystarz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div>
		<%= link_to "Home", root_path %> |
		<%= link_to "Signin", new_user_session_path%> |
		<%= link_to "Signup", new_user_registration_path %> |
		<%= link_to "Logout", destroy_user_session_path, method: :delete %> |
		
	</div>
	    <p class="notice"><%= notice %></p>
       	<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<!--  form_for @project do |f|%>
	 f.text_field :title, placeholder: "Title" %>
	< f.text_area :description, placeholder: "Description" %>
	< f.submit%>
 end %>
 -->
<%= form_for [@recipient, @user] do |f| %>
	<%= f.text_field :title, placeholder: "Title" %>
	<%= f.text_area :description, placeholder: "Description" %>
     <%= f.submit %>
<% end %>

app/views/projects/index.html.erb
<h3><%= link_to "New", new_project_path %></h3>
<% @projects.each do |project| %>
	<div>
		<%= project.user.email %>
		<%= project.title %>
		<%= project.description %>
	</div>
<% end %>

app/views/projects/new.html.erb
<%= render 'projects/form' %>

app/views/projects/show.html.erb
<%= link_to @project.user.email, user_path(@project.user, @user) %>
<div>
	<h4><%= @project.title %></h4>
	<p><%= @project.userforhire %></p>
	<p><%= @project.description %></p>
</div>

app/views/users/_index.html.erb
<% @users.each do |user| %>
	<p><%= link_to user.email, user_path(user) %></p>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.email %></h3>
<p><%= current_user.id%></p>
<p><%= @user.id %></p>

<%= link_to "Send Message", user_projects_path(@user.id) %>

<%= form_for @project do |f| %>
	<%= f.text_field :userforhire, required: true, value: @user.email if current_user  %>
	<%= f.text_field :title, placeholder: "Title" %>
	<%= f.text_field :description, placeholder: "Description" %>
	<%= f.submit%>
<% end %>

app/views/welcomes/index.html.erb
<h3>Hello there!</h3>
<%= render 'users/index' %>